name: Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: 'jdk+fx'

      - name: Cache local Maven repository and JDK cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            target/jdkCache
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run test
        run: ./mvnw test
